ENV['dbuser']='database1'
ENV['dbpassword']='database123'
ENV['domain']='localhost'
ENV['dbport']= '5432'
ENV['dbname']='testdatabase'
ENV['db']='testdatabase.cpdneptoktvs.us-west-2.rds.amazonaws.com'
